### ISSUE TITLE
Version support 

### ISSUE THREAD

**Issue by lowlydba** [potatoqualitee/mssqlsuite#16]
It would be nice to have access to the 2017 installs (since it supports both docker & accessible dev edition install) so that this can be used for multi version job tests. Shortened links for 2017 [here](https://github.com/Sitecore/docker-images/blob/e1ea95da3d342417f15a1b186695f95e6f1d562e/windows/dependencies/mssql-developer-2017/Dockerfile#L14-L15)

This would also pave the way for adding 2022 support when it comes out of preview.

I can put up a PR for it if it sounds good!

**Comment by potatoqualitee** [comment]
oh for sure! yes please for all 3 OSes 🙇🏼

**Comment by potatoqualitee** [comment]
please grab the latest branches, as I updated them with @dzsquared's PR 🙏🏼

**Comment by potatoqualitee** [comment]
WOO! Published
