### ISSUE TITLE
Fails on macOS-latest (virtualbox)

### ISSUE THREAD

**Issue by jamwil** [potatoqualitee/mssqlsuite#6]
Thank-you for making this! I get the following error on the macOS implementation when it tries to start docker-machine:

`Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"`

I have forked the repo and tried inserting `brew install --cask virtualbox` but ran into errors with that as well. Any ideas? I'm happy to submit a PR, but I'm stumped. You can see the full log from my feeble attempt at a fix here: https://github.com/jamwil/mssqlsuite/actions/runs/1963831627

**Comment by potatoqualitee** [comment]
noooooo, i need to run my tests every few months. so much changes. perhaps github added docker support. ill dig.

**Comment by jamwil** [comment]
Thanks for fixing this so quickly!
