### ISSUE TITLE
Request: Use higher priv service account on Windows

### ISSUE THREAD

**Issue by lowlydba** [potatoqualitee/mssqlsuite#9]
I'm dipping my toes into testing some AG functionality using this install, but keep hitting the following error:

> Configuring Availability Group failed: Windows NT user or group 'NT AUTHORITY\NETWORKSERVICE' not found. Check the name again.

Switching the service account to use `LocalSystem` seems to have resolved it. Since this is on a CI agent, I don't think there are any concerns with using a higher privileged service account.

Best option may be to provision a dedicated account, but that may be overkill.

**Comment by potatoqualitee** [comment]
wow, cool! please feel free to submit a PR to make it use `localsystem`. how are you using this that way, btw?

**Comment by lowlydba** [comment]
In this [PR](https://github.com/lowlydba/lowlydba.sqlserver/pull/58) I'm working on getting AG related functionality in my Ansible collection working. It leverages DBATools to allow high level configuration and maintenance of SQL Server either locally or remotely.

**Comment by lowlydba** [comment]
So, as it turns out the localsystem/system account still has issues for a very narrow use case of mine. This initial change fixed the permissions needed to create an AG, but causes downstream issues when using dbatools to create an availability group in non-interactive mode on the github runner.

Happy to do another PR (sorry the first one had the wrong string for the system account!) but also I may be the only one who needs it, so no worries either way! 

As noted [here](https://github.com/lowlydba/lowlydba.sqlserver/pull/58#issuecomment-1104697020), when trying to create an AG with dbatools and the service account as 'NT AUTHORITY\SYSTEM' it gets returned to PowerShell as '[LocalSystem](https://docs.microsoft.com/en-us/windows/win32/services/localsystem-account)' and that is the login that tries to get created/permissioned when Grant-DbaAgPermission is called. Since the 'LocalSystem' looks like a SQL Login, it will prompt for a password to create the login, which is a breaking point if this is being run in NonInteractive mode (like all Ansible scripts are in my case). 

If SQL Server is running under `NT SERVICE\MSSQLSERVER` though, the AG creation works and the permission granting works as intended in non-interactive mode.

**Comment by potatoqualitee** [comment]
ohh interesting! is that something that we need to fix in dbatools or in this repo? I'm happy with a PR for either.

**Comment by lowlydba** [comment]
I think just changing the service account to MSSQLSERVER in this action should avoid it 👍🏻 

Its a pretty small edge case for DBATools to handle, but it could have extra logic to detect 'LocalSystem' and translate that to the NT AUTHORITY equivalent when doing login/permissioning work for the AG.

**Comment by potatoqualitee** [comment]
published in 1.3 along with another feature to allow specific collations! 🥳

**Comment by lowlydba** [comment]
This is working great now, thanks a ton!
